# Generated by Django 5.2.4 on 2025-09-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitem', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('prate', models.IntegerField(blank=True)),
                ('pqty', models.CharField(max_length=100)),
                ('quandity', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordernow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('streetaddress', models.CharField(max_length=100)),
                ('mobilenumber', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('totalvalue', models.IntegerField(blank=True)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, default='images.jpeg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitem', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('prate', models.IntegerField(blank=True)),
                ('pqty', models.CharField(max_length=100)),
                ('banner', models.ImageField(blank=True, default='images.jpeg', upload_to='')),
            ],
        ),
    ]
