# Generated by Django 5.2.4 on 2025-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
