# Generated by Django 5.2.4 on 2025-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_ordernow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/'),
        ),
    ]
